In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [8]:
print(x)

[['Japanese' 12.0 937846.0]
 ['India' 45.0 1224.0]
 ['Rusia' 50.0 56000.0]
 ['Ukraina' 65.0 45000.0]
 ['Mesir' 567.0 nan]
 ['Spanyol' 46.0 50000.0]
 ['Zimbabue' nan 86000.0]]


In [9]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No']


In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:, 1:3] =imputer.transform(x[:,1:3])

In [11]:
print(x)

[['Japanese' 12.0 937846.0]
 ['India' 45.0 1224.0]
 ['Rusia' 50.0 56000.0]
 ['Ukraina' 65.0 45000.0]
 ['Mesir' 567.0 196011.66666666666]
 ['Spanyol' 46.0 50000.0]
 ['Zimbabue' 130.83333333333334 86000.0]]


In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 12.0 937846.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 45.0 1224.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 50.0 56000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 65.0 45000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 567.0 196011.66666666666]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 46.0 50000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 130.83333333333334 86000.0]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:


print(y)



[0 1 0 0 1 1 0]


In [16]:


from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=1)



In [17]:
print(x_train)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 45.0 1224.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 12.0 937846.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 567.0 196011.66666666666]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 65.0 45000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 46.0 50000.0]]


In [18]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 130.83333333333334 86000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 50.0 56000.0]]


In [19]:
print(y_train)

[1 0 1 0 1]


In [20]:
print(y_test)

[0 0]


In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:] = sc.transform(x_test[:,3:])

In [22]:
print(x_train)

[[1.0 0.0 0.0 0.0 -0.5 -0.5 0.0 -0.48412073708518993 -0.6952296697260459]
 [0.0 1.0 0.0 0.0 -0.5 -0.5 0.0 -0.6407480343774573 1.9648512031150775]
 [0.0 0.0 1.0 0.0 -0.5 -0.5 0.0 1.9934383291743114 -0.14201722504147474]
 [0.0 0.0 0.0 0.0 -0.5 2.0 0.0 -0.3891951023626037 -0.5709023527406527]
 [0.0 0.0 0.0 0.0 2.0 -0.5 0.0 -0.47937445534906065 -0.5567019556069044]]


In [23]:


print(x_test)



[[0.0 0.0 0.0 0.0 -0.5 -0.5 1.0 -0.07673155473409052 -0.45445909624391645]
 [0.0 0.0 0.0 1.0 -0.5 -0.5 0.0 -0.4603893284045434 -0.5396614790464064]]
